version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/kubicorn/kubicorn

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check headers
          command: make check-headers
      - run:
          name: Check go files
          command: make check-code
      - run:
          name: Compile
          command: make compile
      - run:
          name: CI
          command: |
            make ci-req && make ci
